### PR TITLE
Latest Changes

### PR DESCRIPTION
**Pull request by mtaylor**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@mtaylor Can you remove and add to git ignore .sass-cache dir (i dont think these should be in dir, and just are build artifacts)

**Comment by mtaylor** [comment]
@michaelandrepearce All that .sass-cache stuff is removing it not adding it.

**Comment by michaelandrepearce** [comment]
Oh (embarressed face)

**Comment by michaelandrepearce** [comment]
merged.

**Comment by michaelandrepearce** [comment]
@mtaylor i added, yourself , clebert and howard as collaborators so hopefully you all should be able to merge without me. (let me know if anyone else i should add)

**Pull request merged**
